# Default values for generic-kafka app
image:
  repository: ghcr.io/organization/app-name
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

kafka:
  servers: "kafka-cluster-kafka-bootstrap:9092"
  security:
    enabled: false
    ssl:
      enabled: false
    sasl:
      enabled: false
  topics:
    - name: "default-topic"
      partitions: 3
      replicationFactor: 1
  consumer:
    groupId: "default-group"
    autoOffsetReset: "earliest"
    enableAutoCommit: true
  producer:
    acks: "all"
    retries: 3
    batchSize: 16384
    compression: "snappy"

application:
  type: "producer"  # or consumer
  config:
    defaultPollTimeout: 1000
    messageFormat: "json"  # or avro, protobuf
    customConfig: {}

monitoring:
  enabled: true
  port: 8000
  path: /metrics

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 8000

deployment:
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  probes:
    enabled: true
    liveness:
      enabled: true
      path: /health/live
    readiness:
      enabled: true
      path: /health/ready

metrics:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: "15s"
  kafka:
    enabled: true
    topics:
      - name: ".*"
        labels:
          app: "kafka-app"