# Default values for generic-kafka app
image:
  repository: ghcr.io/organization/app-name
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

kafka:
  # Serveur Kafka de l'environnement
  servers: "kafka-dev-service.kafka-dev.svc.cluster.local:9092"
  security:
    enabled: false
    ssl:
      enabled: false
    sasl:
      enabled: false
  topics:
    - name: "finance-price-stream"  # Le nom du topic à créer
      partitions: 3                 # Nombre de partitions du topic
      replicationFactor: 1          # Facteur de réplication à 1 (car vous avez un seul broker en dev)
  consumer:
    groupId: "default-group"
    autoOffsetReset: "earliest"
    enableAutoCommit: true
  producer:
    acks: "all"
    retries: 3
    batchSize: 16384
    compression: "snappy"

application:
  type: "producer"  # ou "consumer" selon votre application
  config:
    defaultPollTimeout: 1000
    messageFormat: "json"  # ou avro, protobuf
    customConfig: {}

monitoring:
  enabled: true
  port: 8000
  path: /metrics

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 8000

deployment:
  replicas: 1  # En environnement de développement, un seul réplica de l'application
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  probes:
    enabled: true
    liveness:
      enabled: true
      path: /health/live
    readiness:
      enabled: true
      path: /health/ready

metrics:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: "15s"
  kafka:
    enabled: true
    topics:
      - name: ".*"
        labels:
          app: "kafka-app"