apiVersion: v1
kind: Service
metadata:
  name: {{ include "finance-price-streamer.name" . }}
  labels:
    {{- include "finance-price-streamer.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "finance-price-streamer.labels" . | nindent 4 }}