apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-app.fullname" . }}
  labels:
    {{- include "kafka-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.monitoring.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "kafka-app.selectorLabels" . | nindent 4 }}