# base/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: streamer-config
data:
  KAFKA_SERVERS: "kafka-cluster-kafka-bootstrap:9092"
  DEFAULT_SYMBOL: "JPY"
  DEFAULT_DAYS: "3"
  DEFAULT_SPEED: "1.0"