# base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: finance-price-streamer
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: finance-price-streamer